language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
